# Generated by Django 6.0 on 2026-02-22 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("action", models.TextField()),
                ("is_pleasant", models.BooleanField(default=False)),
                ("periodicity", models.PositiveSmallIntegerField(default=1)),
                ("reward", models.CharField(blank=True, max_length=255, null=True)),
                ("duration", models.PositiveSmallIntegerField()),
                ("is_public", models.BooleanField(default=False)),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="habits.habit"
                    ),
                ),
            ],
        ),
    ]
