# Generated by Django 6.0 on 2026-02-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["time"], "verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
    ]
